pipeline{
    agent any

    stages{
        stage("Build"){
            
            steps{
                dir("build_java"){
                    sh "mvn -version"
                    sh "mvn clean install"
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
