pipeline{
    agent any

    stages{
        stage("Build"){
            
            steps{
                dir("spring-boot-docker/"){
                    sh echo "COMPILANDO"
                    sh "mvn -version"
                    sh "mvn clean install"
                }
            }
        }

        stage("Docker"){
            steps{
                dir("spring-boot-docker/"){
                    sh echo "CREANDO DOCKER"
                    sh "docker-compose up -d --build"
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
